CREATE TABLE IF NOT EXISTS order(
     orderNum INT NOT NULL AUTO_INCREMENT,
     id VARCHAR NOT NULL,
     indate DATETIME NULL DEFAULT now(),
     prodNum INT NOT NULL AUTO_INCREMENT,
     quantity INT NOT NULL AUTO_INCREMENT,
     result CHAR(1) DEFAUTL 1,
     PRIMARY KEY(orderNum)
     CONSTRAINT  fk_id FOREIGN KEY(id) REFERENCE user(id),
     CONSTRAINT  fk_prodNum FOREIGN KEY(prodNum) REFERENCE product(prodNum));

CREATE SEQUENCE order_seq START WITH 1 INCREMENT BY 1;
