# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Test-actions

on:
  # main branch에 push될 때마다 실행
  push:
    branches: ['main']
  # main branch에 PR이 올 때마다 실행
  pull_request:
    branches: ['main']

jobs:
  # test 실행
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          # cache: 'npm'
      - run: 'echo test success'
      # 백엔드 실행
      - name: Run Node
        run: |
          cd ./rootfit_server
          if [ -d "rootfit_server" ]; then
            npm install
            npx nodemon app.js
            echo "Successed Node"
          else
            echo "Failed Node"
          fi

      # 프론트 실행
      - name: Run React
        run: |
          cd ./rootfit_front
          if [ -d "rootfit_front" ]; then
            npm install
            npm run build
            npm run dev
            echo "Successed React"
          else
            echo "Failed React"
          fi

      # 백엔드 실행
      # - name: Run Node
      #   run: (ls /rootfit_server && echo Successed Node) || (echo Failed Node)
      # 프론트 실행
      # - name: Run React
      #   run: (ls /rootfit_front && echo Successed React) || (echo Failed React)
    